-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("dms ipc wallpaperCarousel open"))
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "Spotlight Bar: Toggle" })
hl.unbind("SUPER + SHIFT + P")
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("dms ipc outputs cycleProfile"), { description = "dms ipc outputs cycleProfile" })
hl.unbind("SUPER + SHIFT + Tab")
hl.bind("SUPER + SHIFT + Tab", hl.dsp.workspace.move({ monitor = "+1" }), { description = "Move Workspace to Monitor" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"), { description = "ghostty" })
hl.unbind("SUPER + SHIFT + B")
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("chromium-browser"), { description = "Chromium" })
hl.unbind("SUPER + SHIFT + F")
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("nautilus"), { description = "Nautilus" })
hl.unbind("SUPER + SHIFT + I")
hl.bind("SUPER + SHIFT + I", hl.dsp.exec_cmd("exec ghostty -e btop"))
hl.unbind("SUPER + SHIFT + M")
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("spotify"), { description = "Spotify" })
hl.unbind("ALT + space")
hl.unbind("CTRL + ALT + Delete")
hl.unbind("CTRL + SHIFT + R")
hl.unbind("SUPER + CTRL + F")
hl.unbind("SUPER + CTRL + I")
hl.unbind("SUPER + CTRL + U")
hl.unbind("SUPER + CTRL + mouse_down")
hl.unbind("SUPER + CTRL + mouse_up")
hl.unbind("SUPER + CTRL + down")
hl.unbind("SUPER + CTRL + up")
hl.unbind("SUPER + F")
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle maximization" })
hl.unbind("SUPER + P")
hl.unbind("SUPER + SHIFT + Page_Down")
hl.unbind("SUPER + SHIFT + Page_Up")
hl.unbind("SUPER + SHIFT + U")
hl.unbind("SUPER + T")
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.window.close(), { description = "Close window" })
