#!/usr/bin/env bash

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
PLUGIN_DIR="$CONFIG_DIR/plugins"
THEME_DIR="$CONFIG_DIR/themes"

##############################
#  Theme                      #
##############################
# All colors, fonts and spacing live in themes/*.sh so a new look can be
# applied by swapping the sourced file (or overriding $THEME).

THEME="${THEME:-mono}"
# shellcheck source=themes/mono.sh
source "$THEME_DIR/$THEME.sh"

##############################
#  Bar – Noctalia-style       #
##############################
# Layout mirrors the Noctalia bar.default config order:
#   start  = launcher
#   center = media, cpu, memory (stand-ins for temp/sysmon_2/sysmon_3)
#   end    = network (wifi, bluetooth), volume, clock, session (power), battery

sketchybar --bar position=top \
  height="$BAR_HEIGHT" \
  color="$COLOR_BAR_BG" \
  shadow=off \
  sticky=on \
  margin="$BAR_MARGIN" \
  padding_left="$BAR_PADDING_LEFT" \
  padding_right="$BAR_PADDING_RIGHT" \
  corner_radius="$BAR_CORNER_RADIUS" \
  border_width="$BAR_BORDER_WIDTH" \
  blur_radius="$BAR_BLUR_RADIUS" \
  y_offset="$BAR_Y_OFFSET"

################################
#  Global defaults             #
################################

default=(
  padding_left="$ITEM_PADDING_LEFT"
  padding_right="$ITEM_PADDING_RIGHT"

  icon.font="$FONT_ICON"
  label.font="$FONT_LABEL"

  icon.font.size="$FONT_SIZE_ICON"
  label.font.size="$FONT_SIZE_LABEL"

  icon.color="$COLOR_ICON"
  label.color="$COLOR_LABEL"

  icon.padding_left="$ICON_PADDING_LEFT"
  icon.padding_right="$ICON_PADDING_RIGHT"
  label.padding_left="$LABEL_PADDING_LEFT"
  label.padding_right="$LABEL_PADDING_RIGHT"

  background.drawing=off
  background.border_width=0
)

sketchybar --default "${default[@]}"

################################
#  START: Launcher              #
################################

sketchybar --add item launcher left \
  --set launcher icon=󰚌 \
  icon.font.size=20.0 \
  label.drawing=off

#################################################
#  CENTER: Media, CPU, Memory (noctalia sysmon)  #
#################################################
# When the display has a notch (NOTCH_SPACING=true), this group is placed in
# the left section instead, so it doesn't get hidden behind it.

CENTER_SECTION="center"
if [ "$NOTCH_SPACING" = "true" ]; then
  CENTER_SECTION="left"
fi

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
POPUP_SCRIPT="sketchybar -m --set \$NAME popup.drawing=toggle"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify.name "$CENTER_SECTION" \
  --set spotify.name icon=󰓇 \
  icon.font.size=15.0 \
  label="Not Playing" \
  update_freq=5 \
  script="$PLUGIN_DIR/spotify.sh" \
  click_script="$POPUP_SCRIPT" \
  popup.horizontal=on \
  popup.align=center \
  popup.background.color="$COLOR_POPUP_BG" \
  popup.background.corner_radius="$POPUP_CORNER_RADIUS" \
  popup.background.border_width="$POPUP_BORDER_WIDTH" \
  popup.background.shadow.drawing=off \
  --subscribe spotify.name spotify_change system_woke

controls=("back:󰒮" "play:󰐊" "next:󰒭" "shuffle:󰒝" "repeat:󰑖")

for ctrl in "${controls[@]}"; do
  IFS=':' read -r name icon <<<"$ctrl"

  sketchybar --add item "spotify.$name" popup.spotify.name \
    --set "spotify.$name" icon="$icon" \
    icon.font.size=15.0 \
    label.drawing=off \
    updates=on \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe "spotify.$name" mouse.clicked spotify_change
done

sketchybar --add item cpu "$CENTER_SECTION" \
  --set cpu icon=󰻠 \
  update_freq=5 \
  script="$PLUGIN_DIR/cpu.sh" \
  --subscribe cpu system_woke

sketchybar --add item memory "$CENTER_SECTION" \
  --set memory icon=󰍛 \
  update_freq=5 \
  script="$PLUGIN_DIR/memory.sh" \
  --subscribe memory system_woke

################################################
#  END: Network, Volume, Clock, Session, Battery #
################################################

sketchybar --add item battery right \
  --set battery icon=󰁹 \
  update_freq=60 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --add item power right \
  --set power icon=󰐥 \
  label.drawing=off \
  click_script="$POWER_POPUP_SCRIPT" \
  popup.align=center \
  popup.background.color="$COLOR_POPUP_BG" \
  popup.background.corner_radius="$POPUP_CORNER_RADIUS" \
  popup.background.border_width="$POPUP_BORDER_WIDTH" \
  popup.background.shadow.drawing=off

power_actions=("lock:󰌾" "sleep:󰤄" "logout:󰍃" "reboot:󰑐" "shutdown:󰐥")

for action in "${power_actions[@]}"; do
  IFS=':' read -r name icon <<<"$action"

  sketchybar --add item "power.$name" popup.power \
    --set "power.$name" icon="$icon" \
    label="$name" \
    script="$PLUGIN_DIR/power.sh" \
    --subscribe "power.$name" mouse.clicked
done

sketchybar --add item time right \
  --set time update_freq=10 \
  icon= \
  script="$PLUGIN_DIR/clock.sh"

POWER_POPUP_SCRIPT="sketchybar -m --set \$NAME popup.drawing=toggle"

sketchybar --add item volume right \
  --set volume icon=󰕾 \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item wifi right \
  --set wifi icon=󰤨 \
  update_freq=30 \
  script="$PLUGIN_DIR/wifi.sh" \
  click_script="open x-apple.systempreferences:com.apple.wifi-settings" \
  --subscribe wifi wifi_change

sketchybar --add item bluetooth right \
  --add event bluetooth_status "com.apple.bluetooth.status" \
  --set bluetooth icon=󰂯 \
  label.drawing=off \
  update_freq=30 \
  script="$PLUGIN_DIR/bluetooth.sh" \
  click_script="open x-apple.systempreferences:com.apple.preferences.Bluetooth" \
  --subscribe bluetooth bluetooth_status

#################
#  Final launch #
#################

sketchybar --update
