-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1200@60.00", position = "2688x1440", scale = 1.00 })
hl.monitor({ output = "HDMI-A-1", mode = "3440x1440@59.97", position = "1920x0", scale = 1.00 })
