local function ensure_lazygit_config()
  local out = vim.fn.system({ "lazygit", "-cd" })
  if vim.v.shell_error ~= 0 then
    return
  end
  local config_dir = vim.trim(vim.split(out, "\n", { plain = true })[1])
  local config_path = config_dir .. "/config.yml"

  -- never clobber a config the user actually wrote
  local exists = vim.fn.filereadable(config_path) == 1
  if exists then
    local head = vim.trim((vim.fn.readfile(config_path, "", 1) or { "" })[1] or "")
    if head ~= "" and not vim.startswith(head, "# nvim:") then
      return
    end
  end

  local script = vim.fn.stdpath("config") .. "/bin/ai-commit.sh"
  local yaml = {
    "# nvim: generated by lua/plugins/lazygit.lua - edit there, not here",
    "customCommands:",
    '  - key: "A"',
    '    context: "files"',
    '    description: "Generate AI commit message"',
    "    prompts:",
    '      - type: "input"',
    '        title: "AI commit message"',
    '        key: "Message"',
    string.format('        initialValue: \'{{ runCommand "%s" }}\'', script),
    '    command: "git commit -m {{.Form.Message | quote}}"',
    '    loadingText: "Generating commit message with AI..."',
  }
  vim.fn.mkdir(config_dir, "p")
  vim.fn.writefile(yaml, config_path)
end

return {
  {
    "folke/snacks.nvim",
    init = ensure_lazygit_config,
  },
}
